# SITE CONFIGURATION
baseurl: ""
url: "https://illusion0001.github.io"
title: illusion's Blog
description: "" # used by search engines
permalink: pretty


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: illusion's Blog
  avatar: assets/icons/favicon.svg

  # Header and footer text
  header_text: Detailing the inner workings of my creations.
  header_feature_image: assets/images/banners/lis-butterfly-banner.png
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true
  email_address: illusion3185@gmail.com
  behance:
  bitbucket:
  dribbble:
  discord: 192940192133414912
  facebook:
  flickr:
  gitlab:
  github: illusion0001
  github_sponsors: false
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  patreon: illusion0001
  paypal: 
  reddit: illusion0001
  soundcloud:
  stack_exchange:  # Full URL
  steam: 
  tumblr:
  twitter: illusion0002
  vimeo:
  wordpress:
  youtube: illusion0001

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus:
    tumblr:
    pinterest:
    pocket:
    reddit: true
    hacker_news: true
    linkedin:
    wordpress:
    email:

  # Scripts / Features
  google_analytics: UA-189385610-1
  katex:

  special_page:
    search:
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    categories:
      icon: "tags"
      enabled: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_discord: "Contact on Discord"
  str_support_via: "Support via"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  
  # Icons for buttons
  download_icon: "<i class='fas fa-download'></i>"
  github_icon: "<i class='fab fa-github'></i>"
  docs_icon: "<i class='fas fa-book'></i>"
  gtaf_icon: "<i class='fas icomoon icon-gtaf'></i>"
  codemasters_icon: "<i class='fas icomoon icon-codemasters'></i>"

  # Flags
  pl_flag: "<img style='height:1em;padding: 0 0.5em' src='/assets/images/svg/flags/pl.svg' alt='PL'>"
  gb_flag: "<img style='height:1em;padding: 0 0.5em' src='/assets/images/svg/flags/gb.svg' alt='GB'>"
  eu_flag: "<img style='height:1em;padding: 0 0.5em' src='/assets/images/svg/flags/eu.svg' alt='EU'>"
  us_flag: "<img style='height:1em;padding: 0 0.5em' src='/assets/images/svg/flags/us.svg' alt='US'>"
  jp_flag: "<img style='height:1em;padding: 0 0.5em' src='/assets/images/svg/flags/jp.svg' alt='JP'>"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true


# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

collections:
  mods:
  games:
    output: true
    permalink: /mods/:name/
  portfolio:
    output: true

# SEO
twitter:
  username: 
  card: summary

social:
  name: 
  links:
    - 
    - 

defaults:
  - scope:
      path: ""
    values:
      image: assets/icons/favicon.svg
      date-format: "%B %-d, %Y"
  - scope:
      path: ""
      type: "games"
    values:
      game-series: ""
      parent-series: ""
      order: 0
  - scope:
      path: ""
      type: "mods"
    values:
      excerpt: ""


# PORTFOLIO



# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-gist, jekyll-paginate, jekyll-seo-tag, jekyll-redirect-from, jekyll-feed]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js", ".idea/*", "scratch", "_patches/*"]
